# Generated by Django 3.2.9 on 2021-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
